export const AXIOS_URL = 'https://localhost:44352';

export const CONTEXT_TYPE = {
    SET_USER: "SET_USER",
    SET_STORES: "SET_STORES",
    ADD_STORES: "ADD_STORES",
    REMOVE_STORE: "REMOVE_STORE",
    EDIT_STORE: "EDIT_STORE",
    SET_FEATURE: "SET_FEATURE",
    ADD_FEATURE: "ADD_FEATURE",
    REMOVE_FEATURE: "REMOVE_FEATURE",
    EDIT_FEATURE: "EDIT_FEATURE",
    MODAL_STORE: "MODAL_STORE",
    MODAL_FEATURE: "MODAL_FEATURE"
}
